# Generated by Django 4.2.3 on 2025-10-18 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="namespace",
            unique_together={("organization", "name")},
        ),
    ]
